#
# Module manifest for module 'gcInSpec'
#
# Generated by: Azure Guest Configuration
#
# Generated on: 5/16/2019
#

@{

# Script module or binary module file associated with this manifest.
RootModule = ''

# Version number of this module.
ModuleVersion = '2.0.0'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = '9f4f87f0-8a15-4636-8229-9fd6b50e4460'

# Author of this module
Author = 'Azure Guest Configuration'

# Company or vendor of this module
CompanyName = 'Microsoft Corporation'

# Copyright statement for this module
Copyright = '2019'

# Description of the functionality provided by this module
Description = 'Audits settings based on InSpec profile and returns results. Please review the Chef Terms and Conditions for InSpec and license appropriately.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @(@{ModuleName='GuestConfiguration';ModuleVersion='1.20.0'})

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = ''

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = ''

# Variables to export from this module
VariablesToExport = ''

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = ''

# DSC resources to export from this module
DscResourcesToExport = 'gcInSpec'

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'GuestConfiguration', 'DSC'

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/microsoft/gcInSpec/blob/master/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/microsoft/gcinspec'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = '
        2.0.0
        - Add support for declaring InSpec version
        - Quality and refactoring
        - Breaking changes: paramter names
        
        1.0.0.0
         - Functional MVP for ChefConf demo
        '

    } # End of PSData hashtable

} # End of PrivateData hashtable

}

