instance of gcInSpec as $gcInSpec1ref
{
ResourceID = "[gcInSpec]wmi_service";
 WindowsServerVersion = "2016";
 SourceInfo = "/Users/migreene/Git/gcinspec/examples/wmi_service.ps1::6::9::gcInSpec";
 InSpecProfileName = "wmi_service";
 ModuleName = "gcinspec";
 ModuleVersion = "2.0.0";
 InSpecVersion = "3.9.3";
ConfigurationName = "wmi_service";
};
instance of OMI_ConfigurationDocument

{
    Version="2.0.0";
    MinimumCompatibleVersion = "1.0.0";
    CompatibleVersionAdditionalProperties= {"Omi_BaseResource:ConfigurationName"};
    Name="wmi_service";
};
